### ISSUE TITLE
MPU operations wrapped in CompletionException

### ISSUE THREAD

**Issue by ahmarsuhail** [aws/amazon-s3-encryption-client-java#165]
### Problem:

Related to https://github.com/aws/amazon-s3-encryption-client-java/issues/160 , abort MPU operation is still wrapped in a `CompletionException`.  Trying to abort a MPU without an invalid uploadID gives `java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.NoSuchUploadException: The specified upload does not exist.`

**Comment by justplaz** [comment]
Addressed in https://github.com/aws/amazon-s3-encryption-client-java/pull/174
Released in https://github.com/aws/amazon-s3-encryption-client-java/releases/tag/v3.1.0
