### ISSUE TITLE
S3EncryptionClient.putObject() leaves lingering threads even after closing the client

### ISSUE THREAD

**Issue by soya-miyoshi** [aws/amazon-s3-encryption-client-java#178]
### Problem:

When using the S3EncryptionClient.putObject() method to upload a file to an S3 bucket, I've observed that some threads continue running even after the operation completes and the v3Client.close() method is invoked. This behavior suggests that certain threads spawned by the SDK are not being terminated as expected.

#### Reproduction steps 
https://github.com/aws/amazon-s3-encryption-client-java/blob/main/src/examples/java/software/amazon/encryption/s3/examples/PartialKeyPairExample.java
Invocation of this example code will reproduce this issue.

### Solution:
As a workaround, I used S3AsyncEncryptionClient instead. 

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by lucasmcdonald3** [comment]
Hi @soya-miyoshi,

Thank you for the report.

We have released version [3.1.1](https://github.com/aws/amazon-s3-encryption-client-java/releases/tag/v3.1.1) with the fix.

Thanks,
Lucas

**Comment by soya-miyoshi** [comment]
Nice work!
