### ISSUE TITLE
High level multipart upload not working

### ISSUE THREAD

**Issue by sid22** [aws/amazon-s3-encryption-client-java#376]
### Security issue notifications

If you discover a potential security issue in the Amazon S3 Encryption Client we ask that you notify AWS Security via our [vulnerability reporting page](https://aws.amazon.com/security/vulnerability-reporting/). Please do **not** create a public GitHub issue.

### Problem:

The example in the repo for high level multi part upload 
https://github.com/aws/amazon-s3-encryption-client-java/blob/main/src/examples/java/software/amazon/encryption/s3/examples/MultipartUploadExample.java#L164

uses BoundedInputStream which is in test/ package of the SDK not in main/ path and so not available.

It is unclear if we attempt to upload say a 1 GB file and pass it as
```

        v3Client.putObject(builder -> builder
                .bucket(BUCKET)
                .overrideConfiguration(withAdditionalConfiguration(encryptionContext))
                .key(objectKey), RequestBody.fromFile(file, fileSize));
```

will the SDK load the entire file into memory and then upload ?

### Solution:

Clarification on `BoundedInputStream` and if it regulates behaviour of load by SDK then documentation.

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by justplaz** [comment]
Hey @sid22,

The SDK does not load the entire file into memory before uploading it. When using high-level multipart upload, the data is written to disk as ciphertext then uploaded as parts, which are themselves streamed. The `BoundedInputStream` is just a utility class to provide a stream of data for testing and example purposes. If you have any further questions, feel free to re-open this issue, or cut another. Thanks!
